I've changed line 26
gunthercox/ChatterBot pull request #2201
Opened 2021-09-20 14:06 UTC by Pencoding1

I thought it need to be changed because some people (like me) will meet this error when run chatterbot.
traceback like:
```
Traceback (most recent call last):
  File "c:/Users/cccc0/Documents/GitHub/Mieno/MienoBot/DiscordBot.py", line 3, in <module>
    from ChatterBot import BotCore
  File "c:\Users\cccc0\Documents\GitHub\Mieno\MienoBot\ChatterBot\BotCore.py", line 6, in <module>
    Mieno = ChatBot('Mieno')
  File "C:\Users\cccc0\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\chatterbot.py", line 28, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "C:\Users\cccc0\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\utils.py", line 33, in initialize_class
    return Class(*args, **kwargs)
    super().__init__(**kwargs)
  File "C:\Users\cccc0\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\storage\storage_adapter.py", line 21, in __init__
    'tagger_language', languages.ENG
  File "C:\Users\cccc0\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\tagging.py", line 13, in __init__
    self.nlp = spacy.load(self.language.ISO_639_1.lower())
  File "C:\Users\cccc0\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "C:\Users\cccc0\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\util.py", line 175, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

2021-09-29 12:52 UTC, 1552937 reviewed
This code solves a problem I had. It seems to work.

2022-01-07 17:52 UTC, Omarzintan reviewed
Same here. Replacing line 26 with these lines solves the same issue in using Chatterbot for me.

2024-01-06 23:30 UTC, gnovaro commented
Before use spacy you need to download base models.
For example:
python3 -m spacy download es_core_news_sm

https://github.com/explosion/spaCy/issues/1721

2024-09-25 10:25 UTC, vignesh1507 requested changes
I agree with the changes, could you add a type hint above your changed code so that everyone could understand what the code does.

2025-02-09 16:35 UTC, gunthercox commented
I've made a similar change in #2389 that I believe will resolve this with a bit more flexibility for different languages:
https://github.com/gunthercox/ChatterBot/pull/2389/files#diff-a30358b68e779ddc228075ea1421f86901a2f3818447a4d905624706b43f42c7R30

2025-02-09 16:35 UTC, closed without merging