added python 3.10 support
gunthercox/ChatterBot pull request #2243
Opened 2022-04-08 21:32 UTC by notChewy1324

2022-04-12 01:04 UTC, GamerOfStrategy approved these changes

2022-04-28 23:53 UTC, trey3p approved these changes

2022-05-10 02:35 UTC, jy-zheng approved these changes

2022-05-10 02:37 UTC, jy-zheng approved these changes

2023-02-18 22:01 UTC, gnovaro approved these changes

2023-11-17 08:02 UTC, lenlino approved these changes

2024-01-06 21:32 UTC, Blaise-93 commented
why is the merging of this awesome work blocked? I am using python 3.10 on Linux, and I don't want to downgrade to <=3.8 version

2024-09-25 10:23 UTC, vignesh1507 requested changes
could you update that to 3.12 maybe?

2025-03-29 18:02 UTC, closed without merging